title: Jinrae Kim
subtitle: (김진래, @zlnre)
# logo: /assets/img/zlnre.JPG
face: assets/img/zlnre1.JPG
# cv: 
description: AI Convergence Major
location: Seoul, Korea
email: jinraek@naver.com
homepage: https://zlnre.github.io
#twitter:
github: https://github.com/zlnre
# linkedin: 
# google_analytics:
theme: jekyll-theme-minimal
# google_scholar: 
# semantic_scholar: 

plugins:
  - jekyll-seo-tag
